# We declare a secret with base64-encoded values. However, you probably want a way to
# inject values from a secrets vault, or at least use env substitution, and probably
# don't want to manually base64-encode all your values either. You can use Helm
# or Kustomize to help you with these. This example excludes it for simplicity.
#
# For documentation of generating secrets with kustomize, see this documentation page:
# https://github.com/kubernetes-sigs/kustomize/blob/master/examples/secretGeneratorPlugin.md.
#
# Make sure that you *NEVER* commit secrets. Use something like environment substitution
# or a secrets manager like Hashicorp Vault to keep the values secret and out of git.
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: laracon2019-env
data:
  APP_DEBUG: dHJ1ZQ== # true
  APP_ENV: ZGV2ZWxvcG1lbnQ= # development
  APP_KEY: YmFzZTY0OjJrRHpxSldvSUJaNzAxTmNCdnZXdDFKbVF1WEZwcjBCSlF1U0ZiY291c0E9Cg== # you'd need to keep this secret in reality
